### ISSUE TITLE
Disable by default

### ISSUE THREAD

**Issue by tbrodbeck** [chrisputnam9/chrome-google-keep-full-screen#14]
Every time I restart my browser Fullscreen is enabled again, even though I had it disabled (I only need it ocasionaly).

Please let me disable fullscreen by default or remeber the last session (enabled of not)

**Comment by chrisputnam9** [comment]
Thanks for pointing this out, @tbrodbeck !

If you're up for it, please test out the [beta version](https://chrome.google.com/webstore/detail/google-keep-full-screen-e/dohfmmgobmpcdphilnikejmefkhbmmdp?hl=en&authuser=0) which addresses this.

You'll want to disable the normal version of the extension first.

We'll push this live in another week or two if no issues are found with it.

**Comment by chrisputnam9** [comment]
1.2.2 is now live and addresses this issue
