### ISSUE TITLE
Can't see the Zoom toggle button in notes footer

### ISSUE THREAD

**Issue by JnLlnd** [chrisputnam9/chrome-google-keep-full-screen#17]
Hi. Great extension. Thanks.

I can't see the Zoom toggle button in notes footer. I could not find an option to enable this. Am I missing something?

Using Chrome Version 102.0.5005.63 (Build officiel) (64 bits) French version.

**Comment by chrisputnam9** [comment]
Hi, @JnLlnd !

Strange - I will see if I can test out that specific version.

Meanwhile, are you able to:

1. Confirm you are at https://keep.google.com/ (eg. NOT using the Google Keep App)
2. Take a screenshot of the note and it's footer icons and attach i there.

Thanks!

**Comment by JnLlnd** [comment]
Hi Chris. Thanks for quick reply. I'm on https://keep.google.com/u/0/#home
![2022-06-06 18_00_23-Google Keep](https://user-images.githubusercontent.com/5274931/172256511-f98c6cb3-17e5-4d7e-b998-5a5411e2581e.png)

**Comment by chrisputnam9** [comment]
Thank you for that info! I will test out in French - I think there must be some difference in Keep when in French - I'll see what I can figure out!

**Comment by JnLlnd** [comment]
FYI, I tried to disable all other Chrome extensions to see if there was a conflict but it did not solve the issue.

**Comment by chrisputnam9** [comment]
We're able to replicate this by:

1. Changing Google account language at https://myaccount.google.com/language
2. Reloading https://keep.google.com/#home

We confirmed other languages cause the issue to occur as well.

We are debugging and are excited to be able to get this working for non-English speakers!

**Comment by JnLlnd** [comment]
Thanks for the confirmation and for your work.

**Comment by chrisputnam9** [comment]
Firefox is updated - Google is dragging their feet 😬 - but the fix should **hopefully** be available soon!

**Comment by JnLlnd** [comment]
Confirmed with my Windows French Firefox v101.0.1 (64 bits). Waiting Chrome update. Thanks Chris!

**Comment by chrisputnam9** [comment]
1.2.3 is live with the fix confirmed!

Thanks again, @JnLlnd - I really appreciate you reporting this and helping to get it resolved!
