### ISSUE TITLE
[1.3.0] Button background colour doesn't match the others when the Dark Theme is in use

### ISSUE THREAD

**Issue by dylankenneally** [chrisputnam9/chrome-google-keep-full-screen#19]
|Product|Version|
|-|-|
|Google Keep - Full Screen Edit| 1.2.3|
|Google Chrome|Version 103.0.5060.134 (Official Build) (x86_64)|
|OS|macOS Big Sur 11.6.7 (20G630)|

I've noticed that the background colour used for "Full-screen Toggle", when the user hovers over the button, does not match the colour used for the other buttons - when Dark Theme is enabled.

Hover background colour for **def** buttons: RGB 48, 50, 54
Hover background colour for **ext.** button: RGB 42, 42, 43

Note that this does not happen when "Dark theme" is not use - RGB 233, 234, 234 is correctly used.

**Comment by dylankenneally** [comment]
These may help?

- [Material Design](https://material.io/) - Google's style guide/system, being used by Keep
- [Material Design Colour System](https://material.io/design/color/the-color-system.html)
- [Material Design Themeing](https://material.io/design/material-theming/overview.html#material-theming)

**Comment by chrisputnam9** [comment]
Fix is live - thanks again!
