### ISSUE TITLE
[1.3.0] Menu appears in the wrong place?

### ISSUE THREAD

**Issue by dylankenneally** [chrisputnam9/chrome-google-keep-full-screen#20]
|Product|Version|
|-|-|
|Google Keep - Full Screen Edit| 1.2.3|
|Google Chrome|Version 103.0.5060.134 (Official Build) (x86_64)|
|OS|macOS Big Sur 11.6.7 (20G630)|

Couldn't see the menu item that I see in the [gif in the readme](https://raw.githubusercontent.com/chrisputnam9/chrome-google-keep-full-screen/master/images/demo_1.2.1.gif) - until I opened a note with a URL in it. Found the following:

- no menu item on the normal menu with the note open or closed
- menu item on the menu for a link

<img width="699" alt="menu-not-there" src="https://user-images.githubusercontent.com/12589363/180618833-4f14553e-22e0-4ab2-98be-28126cd3507f.png">
<img width="633" alt="menu-where" src="https://user-images.githubusercontent.com/12589363/180618835-fcfed095-5a3f-407f-a708-59f500807081.png">
<img width="420" alt="Screen Shot 2022-07-24 at 4 45 56 am" src="https://user-images.githubusercontent.com/12589363/180618838-161dc54e-f70a-4e84-b8fe-9e2f3401ac55.png">

**Comment by chrisputnam9** [comment]
Thanks a ton, Dylan - this is very helpful!

I suspect this may help us finally address issue #6 as well

**Comment by chrisputnam9** [comment]
Fix is live - thanks for helping track down a tricky issue for me!
