### ISSUE TITLE
Convert to user script if possible

### ISSUE THREAD

**Issue by SocietasEvanescentes** [chrisputnam9/chrome-google-keep-full-screen#21]
If possible, convert this extension to a user script. If you're able to do so, this would reduce burden in a Safari version, and would work in all browsers including Safari for Mobile with the use of extensions on IOS 16+.

**Comment by chrisputnam9** [comment]
Hi, @Rex501st !

Thanks for the suggestion - that does sound beneficial.

I haven't done much with user scripts so far. What, in your opinion, would be the best way to publish it?
Eg. https://greasyfork.org or are there other services you prefer to use?

Thanks!
