### ISSUE TITLE
Laggy when Full Screen on 2nd 4k Monitor

### ISSUE THREAD

**Issue by pagro** [chrisputnam9/chrome-google-keep-full-screen#3]
Just moved to a 4k Monitor and the whole checklist is laggy (unusable) when on full screen. No issues with a 1080p monitor.

Could be the laptop as well, but CPU/RAM usage look normal. Upon removal of the extension, Google Keep works fine.

**Comment by chrisputnam9** [comment]
Thank you for the report - I'll look into it.

**Comment by chrisputnam9** [comment]
@pagro could you confirm the exact resolution you had the issue at, so I can attempt to replicate this?

**Comment by pagro** [comment]
Sure thing - 3840 x 2160.

**Comment by chrisputnam9** [comment]
Hi, @pagro 

I had the chance to test at the same resolution on a 4K monitor today.  I wasn't able to see any difference between full screen and standard - both seemed quite responsive.

It occurs to me that Hardware Acceleration in Chrome could be a concern here.  Would you please try toggling that, relaunching Chrome, and see if that helps?
 - URL: chrome://settings/?search=hardware+acceleration
 - Screenshot: https://cmp.onl/tjow

Assuming that doesn't resolve it, and you have further time to test - would you please try a brand new Chrome profile with GKFS installed, but no other extensions installed?  I hope that this will help us narrow down the issue for you.

Thank you!

**Comment by pagro** [comment]
Toggled Chrome Hardware Acceleration from OFF to ON, relaunched, and it
works!

Thanks for the support, man! Here's to full-screen Google Keep goodness :)
---

**Comment by chrisputnam9** [comment]
Awesome! I'm glad that resolved it. I'll pin this in case others have the same issue.  Thanks!

**Comment by wuayker** [comment]
Hello there and good times bro. I got a serious problem here, I dont know what happen with Chrome but everytime i try to install volumen boost, just does not work. i have one week behind this problem and there is nothing at the intere and whole internet as the geek that I am. The point is that I can see you have "parched" the problem. I mean, is true that by some privacy issues, you cant go full-screen while you sharing a sound extension, I dont know why. watching what you got with google keep full-screen, and you also said we can modify it, is there a way to solve it ? 

I left you a picture, I even format the machine to solve it and nothing... today I find what I knew was going on but... no body is talking it on Internet.
![THE PROOF I KNEW IT](https://user-images.githubusercontent.com/79172062/108126917-0bb52100-7070-11eb-9248-6beb4a75c513.jpg)

**Comment by wuayker** [comment]
As you can see I even download Brave and it lauches me same error... 
other question just a doupt 

does anything of all this full screen crap has something to do with IPFS Support??? 

greeting my friend and EXITO
