### ISSUE TITLE
Adding full screen button to the "Take a note... " new note section

### ISSUE THREAD

**Issue by nickfaughey** [chrisputnam9/chrome-google-keep-full-screen#4]
Great work on this extension - it's something that should have been included in the default web app. One tiny improvement I can see is if the functionality could be extended to also work in the "new note" section, as opposed to just in existing notes. Currently, my workflow for when I want to take a note is:

1. Open Keep
2. Click in "Take a Note..."
3. Type temporary garbage: `asd`
4. Close
5. Open temporary note
6. Delete garbage
7. Go fullscreen
8. Take fullscreen notes

It'd be awesome if I could eliminate steps 3-6 to streamline the process from "I want to take a note" to actually typing the note. I'll admit I've given neither the code nor the HTML structure a look yet to see how the "Take a Note..." is different from existing notes, but this feature would be a game changer for me.

**Comment by chrisputnam9** [comment]
Thanks, Nick!
I appreciate the feedback, and I agree, this would be a nice improvement.
I'll put this on my short list.

**Comment by chrisputnam9** [comment]
Are you up for testing the beta version, @nickfaughey ?

It's working well for me, but I'd appreciate additional testing

You'll want to disable the version you have now, and install the beta from this direct link: https://chrome.google.com/webstore/detail/google-keep-full-screen-e/dohfmmgobmpcdphilnikejmefkhbmmdp

**Comment by nickfaughey** [comment]
Works flawlessly. Impressive turnaround!

**Comment by chrisputnam9** [comment]
Thanks, @nickfaughey ! I'll get it merged into production in the next few days.
