### ISSUE TITLE
[1.3.0] Options page usability - not obvious that options is in its own tab

### ISSUE THREAD

**Issue by chrisputnam9** [chrisputnam9/chrome-google-keep-full-screen#40]
From @JnLlnd

> My only comment is about the usability of the Options page. I was trying to
> close the preview page to return to the Keep page but there was no way to
> close it. It took me some time to realize that the preview page was open in
> a new Chrome tab and that I had to close the tab. Maybe a hint about this
> would help.

Ideas:
- Add a note that always shows
- Add a "close" button
- Add a listener when backdrop is clicked (to either close or show a message)
- Maybe also consider a confirmation if trying to close options with unsaved changes

**Comment by chrisputnam9** [comment]
We just pushed an update - version 1.3.1 - to the Beta extension which adds more intuitive (we hope) closing for the options page.

Feedback is welcome as always!

**Comment by chrisputnam9** [comment]
Note: it will take some time - usually less than 24 hours - for the new version to become available.

**Comment by JnLlnd** [comment]
Will we need a direct link to install v1.3.1?

**Comment by chrisputnam9** [comment]
It will be the same:
https://chromewebstore.google.com/detail/beta-google-keep-full-scr/dohfmmgobmpcdphilnikejmefkhbmmdp

Looks like 1.3.1 BETA is published as of now.

**Comment by JnLlnd** [comment]
Tested. Excellent. Thanks.

**Comment by chrisputnam9** [comment]
Wonderful; thanks again, Jean!
