### ISSUE TITLE
Text indentation

### ISSUE THREAD

**Issue by Palivec** [chrisputnam9/chrome-google-keep-full-screen#8]
Hi !
I take notes on laptop widescreen, and all the text is aligned on the left side in long lines, which is not very comfortable. It would be nice to display the text in a block with custom width, positioned in the center. Now I can bypass this by reducing the browser window width but it looks ugly, as it's not a real fullscreen. Thanks !

**Comment by chrisputnam9** [comment]
Thanks for the suggestion!

This is an interesting idea... I'm not sure if it will make sense to add as a feature for this plugin specifically, but I'm going to keep thinking about it!

**Comment by chrisputnam9** [comment]
#9 is very similar - I think I will likely implement this as a setting

**Comment by chrisputnam9** [comment]
Combining into https://github.com/chrisputnam9/chrome-google-keep-full-screen/issues/27
