### ISSUE TITLE
Please add an option for 80% / 70% / 60% width with 100% opacity background

### ISSUE THREAD

**Issue by chrisputnam9** [chrisputnam9/chrome-google-keep-full-screen#9]
Some wider screens make the note too wide.

From suggestion on Webstore - Sean

**Comment by chrisputnam9** [comment]
Similar suggestion:

Make full screen, but shrink text area for more of a "distraction free" effect
I like the app but have you considered adding an option for a more distraction free writing setup? Full screen is great except the text is stretched allll the way across the screen. I ended up editing the app to have it take up 2/3rds of the screen... I think if you made it more of a distraction free full screen you would get a lot of attention. Think something like recommend Simple Note or OmmWriter where it takes up the whole screen, but the text area is smaller in a manageable area to work with and see. Cheers!
Posted by Mason Balistreri - Jul 1

**Comment by chrisputnam9** [comment]
Another similar suggestion from reviews:

Thanks for your work. It's a great idea, and I wish the almighty Google would just let us maximize the note without 3rd party addons. However, I would ask for a custom size here, e.g. 50%, 75%, 100% of the browser window. Ideally, provide a slider to go from 50%to 100% in small increments. On a large monitor the full-screen view is overwhelming and unnecessary, while on a small screen the user may need the 100%.

**Comment by macdonaldster** [comment]
I just found your extension and love this idea. I really enjoy full screen editing but having some margin on the sides so you aren't scanning across the entire monitor makes sense to me. 

Thank you for your work on this extension.

**Comment by chrisputnam9** [comment]
Thanks, @macdonaldster - with multiple requests for this - I do think we'll add it soon.  Hoping to prioritize some time on this within the next few months.

Thank you for the feedback!

**Comment by chrisputnam9** [comment]
Combining into https://github.com/chrisputnam9/chrome-google-keep-full-screen/issues/27

**Comment by chrisputnam9** [comment]
Options are live in 1.3.1!
